services:
  nginx:
    image: nginx:latest
    container_name: nginx-server
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express-app
    ports:
      - "8080:5000"
    environment:
      - PORT=5000
    depends_on:
      - nginx
    restart: always
